apiVersion: nfd.openshift.io/v1
kind: NodeFeatureDiscovery
metadata:
  name: nfd-instance
spec:
  instance: ''
  operand:
    image: registry.redhat.io/openshift4/ose-node-feature-discovery-rhel9:latest
    servicePort: 12000
  topologyUpdater: false
  workerConfig:
    configData: "core:\n  sleepInterval: 60s\nsources:\n  pci:\n    deviceClassWhitelist:\n\
      \      - \"0200\"\n      - \"03\"\n      - \"12\"\n    deviceLabelFields:\n\
      \      - \"vendor\"\n"
