apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rag-pipeline-secrets
spec:
  refreshInterval: 2m0s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: rag-pipeline-secrets
    template:
      type: Opaque
      engineVersion: v2
      data:
        MINIO_ACCESS_KEY: '{{ `{{ .MINIO_ACCESS_KEY }}` }}'
        MINIO_SECRET_KEY: '{{ `{{ .MINIO_SECRET_KEY }}` }}'
        LLAMASTACK_BASE_URL: '{{ `{{ .LLAMASTACK_BASE_URL }}` }}'
        DS_PIPELINE_URL: '{{ `{{ .DS_PIPELINE_URL }}` }}'
        SOURCE: '{{ `{{ .SOURCE }}` }}'
        EMBEDDING_MODEL: '{{ `{{ .EMBEDDING_MODEL }}` }}'
        NAME: '{{ `{{ .NAME }}` }}'
        VERSION: '{{ `{{ .VERSION }}` }}'
        ACCESS_KEY_ID: '{{ `{{ .ACCESS_KEY_ID }}` }}'
        SECRET_ACCESS_KEY: '{{ `{{ .SECRET_ACCESS_KEY }}` }}'
        BUCKET_NAME: '{{ `{{ .BUCKET_NAME }}` }}'
        REGION: '{{ `{{ .REGION }}` }}'
        MINIO_ENDPOINT: '"http://{{ `{{ .host }}` }}.{{ `{{ .Release.Namespace }}`
          }}.svc.cluster.local:{{ `{{ .port }}` }}"'
        ENDPOINT_URL: '"http://{{ `{{ .host }}` }}.{{ `{{ .Release.Namespace }}` }}.svc.cluster.local:{{
          `{{ .port }}` }}"'
  data:
  - secretKey: MINIO_ACCESS_KEY
    remoteRef:
      key: secret/data/hub/configure-pipeline
      property: MINIO_ACCESS_KEY
  - secretKey: MINIO_SECRET_KEY
    remoteRef:
      key: secret/data/hub/configure-pipeline
      property: MINIO_SECRET_KEY
  - secretKey: LLAMASTACK_BASE_URL
    remoteRef:
      key: secret/data/hub/configure-pipeline
      property: LLAMASTACK_BASE_URL
  - secretKey: DS_PIPELINE_URL
    remoteRef:
      key: secret/data/hub/configure-pipeline
      property: DS_PIPELINE_URL
  - secretKey: SOURCE
    remoteRef:
      key: secret/data/hub/configure-pipeline
      property: SOURCE
  - secretKey: EMBEDDING_MODEL
    remoteRef:
      key: secret/data/hub/configure-pipeline
      property: EMBEDDING_MODEL
  - secretKey: NAME
    remoteRef:
      key: secret/data/hub/configure-pipeline
      property: NAME
  - secretKey: VERSION
    remoteRef:
      key: secret/data/hub/configure-pipeline
      property: VERSION
  - secretKey: ACCESS_KEY_ID
    remoteRef:
      key: secret/data/hub/configure-pipeline
      property: ACCESS_KEY_ID
  - secretKey: SECRET_ACCESS_KEY
    remoteRef:
      key: secret/data/hub/configure-pipeline
      property: SECRET_ACCESS_KEY
  - secretKey: BUCKET_NAME
    remoteRef:
      key: secret/data/hub/configure-pipeline
      property: BUCKET_NAME
  - secretKey: REGION
    remoteRef:
      key: secret/data/hub/configure-pipeline
      property: REGION
