apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: llama-stack
spec:
  refreshInterval: 2m0s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: llama-stack
    template:
      type: Opaque
      engineVersion: v2
      data:
        GOOGLE_APPLICATION_CREDENTIALS: '{{ `{{ .GOOGLE_APPLICATION_CREDENTIALS }}`
          }}'
  data:
  - secretKey: GOOGLE_APPLICATION_CREDENTIALS
    remoteRef:
      key: secret/data/hub/llama-stack
      property: GOOGLE_APPLICATION_CREDENTIALS
