apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: huggingface-secret
spec:
  refreshInterval: 2m0s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: huggingface-secret
    template:
      type: Opaque
      engineVersion: v2
      data:
        HF_TOKEN: '{{ `{{ .HF_TOKEN }}` }}'
  data:
  - secretKey: HF_TOKEN
    remoteRef:
      key: secret/data/hub/llm-service
      property: HF_TOKEN
