apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgvector
spec:
  refreshInterval: 2m0s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: pgvector
    template:
      type: Opaque
      engineVersion: v2
      data:
        user: '{{ `{{ .user }}` }}'
        password: '{{ `{{ .password }}` }}'
        host: '{{ `{{ .host }}` }}'
        port: '{{ `{{ .port }}` }}'
        dbname: '{{ `{{ .dbname }}` }}'
        jdbc-uri: jdbc:postgresql://{{ `{{ .host }}` }}.:{{ `{{ .port }}` }}/{{ `{{
          .dbname }}` }}?password={{ `{{ .password }}` }}&user={{ `{{ .user }}` }}
        uri: postgresql://{{ `{{ .user }}` }}:{{ `{{ .password }}` }}@{{ `{{ .host
          }}` }}.:{{ `{{ .port }}` }}/{{ `{{ .dbname }}` }}
  data:
  - secretKey: user
    remoteRef:
      key: secret/data/hub/pgvector
      property: user
  - secretKey: password
    remoteRef:
      key: secret/data/hub/pgvector
      property: password
  - secretKey: host
    remoteRef:
      key: secret/data/hub/pgvector
      property: host
  - secretKey: port
    remoteRef:
      key: secret/data/hub/pgvector
      property: port
  - secretKey: dbname
    remoteRef:
      key: secret/data/hub/pgvector
      property: dbname
